//! Minimal example: esp-wifi-caddy + config crates — connect to WiFi and print config changes.
//!
//! Config: WiFi credentials and example string/integer. Storage in flash (config partition).
//! Boot button (GPIO 0): press toggles AP on/off and serves the HTTP config UI on AP.

#![no_std]
#![no_main]

extern crate alloc;

use alloc::string::String;
use core::str::FromStr;
#[cfg(feature = "defmt")]
use defmt::info;
use embassy_executor::Spawner;
use embassy_time::Duration;
use embassy_time::Timer;
use esp_alloc as _;
use esp_backtrace as _;
use esp_hal::gpio::{InputConfig, Pull};
use esp_hal::timer::timg::TimerGroup;
use esp_println as _;
use esp_storage::FlashStorage;
use esp_wifi_caddy::{WifiApSsidPrefix, WifiPass, WifiSsid};
#[cfg(not(feature = "defmt"))]
use log::info;
use wifi_caddy::ConfigHandle;
use wifi_caddy_proc::WifiCaddyConfig;

esp_bootloader_esp_idf::esp_app_desc!();

/// App config: WiFi credentials and example string and integer.
#[derive(Clone, Debug, Default, WifiCaddyConfig)]
pub struct AppConfig {
    #[config_store(env_default = "WIFI_SSID", notify = "Wifi")]
    #[config_form(page = "Network", fieldset = "WiFi", help = "Network name (SSID)")]
    wifi_ssid: String,
    #[config_store(env_default = "WIFI_PASS", notify = "Wifi")]
    #[config_form(
        page = "Network",
        fieldset = "WiFi",
        input_type = "password",
        help = "WiFi password"
    )]
    wifi_pass: String,
    #[config_store(notify = "Example")]
    #[config_form(page = "Example", fieldset = "Example", help = "String field")]
    example_string: String,
    #[config_store(notify = "Example")]
    #[config_form(page = "Example", fieldset = "Example", help = "Integer field")]
    example_integer: u32,
}

// ConfigKey is generated by ConfigStore derive (Magic, FormatVersion, and field keys).

/// Shared config type (used by config_updated_task).
pub type SharedConfig = ConfigHandle<AppConfig>;

/// Task that awaits config updates and sends WiFi credentials to the wifi manager when Wifi changes.
/// Also reports Example changes.
#[embassy_executor::task]
async fn config_updated_task(
    config_rx: ConfigUpdateReceiver,
    config: SharedConfig,
    wifi_sender: esp_wifi_caddy::WifiCommandSender,
) {
    loop {
        let changed = config_rx.receive().await;
        if changed.contains(ConfigChange::Wifi) {
            let (ssid, pass) = {
                let cfg = config.lock().await;
                (cfg.wifi_ssid().clone(), cfg.wifi_pass().clone())
            };
            if !ssid.is_empty() {
                let _ = wifi_sender
                    .send(esp_wifi_caddy::WifiCaddyCommand::StaUp(
                        WifiSsid::from_str(ssid.as_str())
                            .expect("Failed to convert String to WifiSsid"),
                        WifiPass::from_str(pass.as_str())
                            .expect("Failed to convert String to WifiPass"),
                    ))
                    .await;
            }
        }
        if changed.contains(ConfigChange::Example) {
            let cfg = config.lock().await;
            info!(
                "Example changed: string: {}, integer: {}",
                cfg.example_string().as_str(),
                cfg.example_integer()
            );
        }
    }
}

/// Task that reports IP address changes on the STA interface
#[embassy_executor::task]
async fn ip_address_task(sta: embassy_net::Stack<'static>) {
    let mut last_address = None;
    loop {
        if let Some(ip_config) = sta.config_v4() {
            // report address changes
            if Some(ip_config.address) != last_address {
                info!("main: IP: {}", ip_config.address);
                last_address = Some(ip_config.address);
            }
        }
        Timer::after(Duration::from_millis(1000)).await;
    }
}

#[esp_rtos::main]
async fn main(spawner: Spawner) {
    #[cfg(feature = "log")]
    esp_println::logger::init_logger_from_env();
    let peripherals = esp_hal::init(esp_hal::Config::default());

    esp_alloc::heap_allocator!(#[esp_hal::ram(reclaimed)] size: 64 * 1024);
    esp_alloc::heap_allocator!(size: 16 * 1024);

    let timg0 = TimerGroup::new(peripherals.TIMG0);
    #[cfg(target_arch = "riscv32")]
    let sw_int =
        esp_hal::interrupt::software::SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);
    esp_rtos::start(
        timg0.timer0,
        #[cfg(target_arch = "riscv32")]
        sw_int.software_interrupt0,
    );

    info!("wifi-example starting");

    let flash = FlashStorage::new(peripherals.FLASH);

    #[cfg(any(feature = "esp32s3", feature = "esp32"))]
    let flash = flash.multicore_auto_park();

    let (wifi_stacks, wifi_sender, config, config_rx) =
        esp_wifi_caddy::wifi_init!(AppConfig, spawner, peripherals.WIFI, flash, "config")
            .expect("wifi_init");

    spawner.spawn(ip_address_task(wifi_stacks.sta)).ok();
    info!("IP address task spawned (reports IP changes)");

    {
        let cfg = config.lock().await;
        let ssid = cfg.wifi_ssid().clone();
        if !ssid.is_empty() {
            wifi_sender
                .send(esp_wifi_caddy::WifiCaddyCommand::StaUp(
                    WifiSsid::from_str(ssid.as_str())
                        .expect("Failed to convert String to WifiSsid"),
                    WifiPass::from_str(cfg.wifi_pass().as_str())
                        .expect("Failed to convert String to WifiPass"),
                ))
                .await;
        }
    }
    spawner
        .spawn(config_updated_task(config_rx, config, wifi_sender))
        .ok();
    info!("wifi config task spawned (awaits config updates)");

    let mut button_pin = esp_hal::gpio::Input::new(
        peripherals.GPIO0, // BOOT_BUTTON_GPIO
        InputConfig::default().with_pull(Pull::Up),
    );

    let mut ap_state = false;
    loop {
        button_pin.wait_for_falling_edge().await;
        if ap_state {
            info!("AP down");
            wifi_sender
                .send(esp_wifi_caddy::WifiCaddyCommand::APDown)
                .await;
        } else {
            info!("AP up");
            wifi_sender
                .send(esp_wifi_caddy::WifiCaddyCommand::APUp(
                    WifiApSsidPrefix::from_str("wifi-example-").unwrap(),
                ))
                .await;
        }
        ap_state = !ap_state;
    }
}
