//! Serve the fully-static config page generated by the proc macro.

use crate::config_storage::ConfigFormGen;
use edge_http::io::Error;
use edge_http::io::server::Connection;
use embedded_io_async::{ErrorType, Read, Write};

/// Serve the config page as a single static string.
pub async fn serve_config_page<C, T, const N: usize>(
    conn: &mut Connection<'_, T, N>,
) -> Result<(), Error<<T as ErrorType>::Error>>
where
    C: ConfigFormGen,
    T: Read + Write,
{
    conn.initiate_response(
        200,
        None,
        &[
            ("Content-Type", "text/html; charset=utf-8"),
            ("Connection", "close"),
        ],
    )
    .await?;
    conn.write_all(C::config_page().as_bytes()).await?;
    conn.complete().await
}
